= DocBook Authoring and Publishing Suite (DAPS)

The SUSE Documentation Team <doc-team@suse.com>

image:https://travis-ci.org/openSUSE/daps.svg?branch=master["Build
Status", link="https://travis-ci.org/openSUSE/daps"]

:numbered:
:website: https://github.com/openSUSE/daps
:giturl:  git@github.com:openSUSE/daps.git
:ghpages: http://opensuse.github.io/daps

A complete environment to build HTML, PDF, EPUB and other formats from
DocBook XML. See {website} for more information. Documentation is available
from https://opensuse.github.io/daps/doc/index.html.
DAPS is released under the GPL (version 2 or 3 at your choice).


== Installing DAPS

DAPS packages are available for openSUSE and SUSE Linux Enterprise. It has
also been successfully tested on Debian, Fedora, Linux Mint, and Ubuntu. See
link:INSTALL.adoc[INSTALL.adoc] for installation instructions.

The https://github.com/openSUSE/daps/releases/latest[latest DAPS version].


== Forum

Use the https://github.com/openSUSE/daps/discussions[GitHub Discussions] of this repository.


== Reporting Bugs

To report bugs, use the bug tracker of this repository: https://github.com/openSUSE/daps/issues/new?template=bug.md.


== Contributing

If you would like to contribute to the project, do the following:

. Fork this project.

. Clone the project:
+
    git clone git@github.com:YOUR_USERNAME/daps.git

. Create a new branch from the main branch.

    git branch <BRANCH_NAME> main

. Make your changes.

. Send a pull request. Note that we will only accept pull requests against
  the main branch.
