DAPS Quickstart
===============

:numbered:

To start a new DAPS project `my_article` in `~/authoring` proceed as
follows:

1. Setting up the Project:
+
   $ daps-init --docdir ~/authoring --name "my_article"
+
This will create a complete DAPS working environment for the article
"my_article" in`~/authoring/. The working environment consists of the
following directory structure:
+
   ~/authoring
       |--images/
       |    |--src/
       |    |   |--dia/
       |    |   |--fig/
       |    |   |--jpg/
       |    |   |--pdf/
       |    |   |--png/
       |    |   |--svg/
       |--xml/
+
plus a config file for the article (aka DC-file) named `DC-my_article` and
an example XML document `xml/MAIN-my_article.xml`.

2. Building the Example Article:
* Single HTML-file:
    $ cd ~/authoring
    $ daps -d DC-my_article html --single
* PDF:
    $ cd ~/authoring
    $ daps -d DC-my_article pdf

3. For More Information
* see `daps --help` for an overview of DAPS commands and options
* the DAPS documentation is available at https://opensuse.github.io/daps/doc/
* for information about DocBook, refer to http://docbook.org/

