#!/bin/bash
#
# Copyright (C) 2013 Frank Sundermeyer <fsundermeyer@opensuse.org>
#
# Author:
# Frank Sundermeyer <fsundermeyer@opensuse.org>
#
# Testing DAPS: EPUB
#
#
# * Does EPUB correctly build?
# * Does the name retrieved with *-dir-name match the actual result?
# * Does the EPUB file validate with epubcheck?
# * Does the --css switch work?
# * Does the --check switch validate the epub file?
# * Is the --name option correctly implemented?
# * Does the --rootid option work correctly?
# * Do the --styleroot and --fb_styleroot options work?
# * Does the fallback to a CSS file from the stylesheet directory work?

source lib/common_functions

header "ePUB"

function oneTimeSetUp() {
    # Clean up the build directory
    clean_build
    # get the profiling directory
    _EPUB_PATH=$($_DAPSEXEC -d $_DCFILE epub-name 2>/dev/null)
    if [ $? -ne 0 ]; then
	exit_on_error " The initial DAPS call to determine the path to the resulting ePUB failed. Skipping tests"
    fi
    _LOG_DIR=$($_DAPSEXEC -v0 -d $_DCFILE showvariable VARIABLE=LOG_DIR 2>/dev/null)
    if [ $? -ne 0 ]; then
	exit_on_error " The initial DAPS call to determine the LOG file failed. Skipping tests"
    fi
    _LOGFILE=${_LOG_DIR}/make_epub.log
}

# Post
# this function is run _after_ the tests are executed
#
function oneTimeTearDown() {
    stats
    # Clean up the build directory
    clean_build
}

#---------------------------------------------------------------
# TESTS
#---------------------------------------------------------------

#--------------------------------
# * Does EPUB correctly build?
# * Does the name retrieved with *-dir-name match the actual result?
#
function test_epub () {
    local _EPUB_NAME
    _EPUB_NAME=$($_DAPSEXEC -v0 -d $_DCFILE epub 2>/dev/null)
    assertTrue \
        ' └─ The epub command itself failed' \
        "$?"
    assertTrue \
	" └─ The resulting file (${_EPUBFILE_NAME}) does not exist." \
	"[ -f $_EPUB_NAME ]"
    assertEquals \
	" └─ The resulting filename does not match the one retrieved with --epub-name" \
	"$_EPUB_PATH" "$_EPUB_NAME"
}

#--------------------------------
# * Does the EPUB file validate with epubcheck?

function test_epubValidate () {
    local CHECK_MESSAGE
    CHECK_MESSAGE=$(epubcheck $_EPUB_PATH)
    assertTrue \
        " └─ The generated ePUB file does not validate:\n;;;;;;;;;;\n${CHECK_MESSAGE}\n;;;;;;;;;;" \
        "$?"    
}

#--------------------------------
# * Do the --styleroot and --fb_styleroot options work?
# * Does the automatic fallback to the DoBook stylesheets work? 
#
function test_epubStyleroot () {

     clean_build

    # Testing Fallback Styleroot by specifying a wrong Styleroot dir
    # 

    $_DAPSEXEC -d $_DCFILE --styleroot=${_DOC_DIR} --fb_styleroot=${_STANDARD_STYLES} --debug epub >/dev/null 2>&1
    egrep -q -- "--stylesheet /.*/${_STANDARD_STYLES}" $_LOGFILE 2>/dev/null
    assertTrue \
	" └─ The Fallback Styleroot specified on the command line was not used." \
	"$?"

    clean_build

    # Testing automatic Fallback to _DB_STYLES by specifying a wrong
    # Styleroot dir with no Fallback
    #
    $_DAPSEXEC -d $_DCFILE --styleroot=${_DOC_DIR} --debug epub >/dev/null 2>&1
    grep -q -- "--stylesheet ${_DB_STYLES}" $_LOGFILE 2>/dev/null
    assertTrue \
	" └─ The automatic DocBook Fallback Styleroot was not used." \
	"$?"    

    clean_build

    # Testing Styleroot specified with --styleroot
    #
    eval "$_DAPSEXEC -d $_DCFILE --styleroot ${_STANDARD_STYLES} --debug epub >/dev/null 2>&1"
    egrep -q -- "--stylesheet /.*/${_STANDARD_STYLES}" $_LOGFILE 2>/dev/null
    assertTrue \
	" └─ The Styleroot specified on the command line was not used." \
	"$?"
}


#--------------------------------
# * Does the --css switch work?
#

function test_epubCSS_Check () {
    local _CSS_FILE _CSS_PATH _EPUBPATH_BUILD

    _CSS_CMD_NAME="test.css"
    _CSS_CMD_PATH="${_DOC_DIR}/xml/${_CSS_CMD_NAME}"
    _CSS_DC_NAME="reference.css" # from $_DCFILE
    _CSS_STYLE_NAME="style.css"

    _EPUBPATH_BUILD=""

    # Does the EPUB contain the css file specified in the DC file?
    #

    clean_build
 
    _EPUBPATH_BUILD=$($_DAPSEXEC -d $_DCFILE epub 2>/dev/null)

    unzip -l $_EPUB_PATH 2>/dev/null | grep "$_CSS_DC_NAME" >/dev/null 2>&1
    assertTrue \
        " └─ The resulting ePUB does not include the CSS file specifed in $_DCFILE ($_CSS_DC_NAME)." \
        "$?"

    # Does the EPUB contain the default CSS file from the stylesheet
    # directory when no other CSS file is specified?

    clean_build

    _EPUBPATH_BUILD=$($_DAPSEXEC --main $_MAINPATH --styleroot ${_STANDARD_STYLES} epub 2>/dev/null)
    unzip -l $_EPUBPATH_BUILD 2>/dev/null | grep "$_CSS_STYLE_NAME" >/dev/null 2>&1
    assertTrue \
        " └─ The resulting ePUB does not include the CSS file from the stylesheet directory ($_CSS_STYLE_NAME)." \
        "$?"    

    # Does the EPUB contain the css file specified on the command line?
    #

    clean_build
 
    _EPUBPATH_BUILD=$($_DAPSEXEC -d $_DCFILE epub --css=${_CSS_CMD_PATH} 2>/dev/null)

    unzip -l $_EPUBPATH_BUILD 2>/dev/null | grep "$_CSS_CMD_NAME" >/dev/null 2>&1
    assertTrue \
        " └─ The resulting ePUB does not include the CSS file specified on the command line ($_CSS_CMD_NAME)." \
        "$?"

    # Does the EPUB contain no css file with --css=none?
    #

    clean_build
 
    _EPUBPATH_BUILD=$($_DAPSEXEC -d $_DCFILE epub --css=none 2>/dev/null)

    unzip -l $_EPUBPATH_BUILD 2>/dev/null | grep "\.css" >/dev/null 2>&1
    assertFalse \
        " └─ The resulting ePUB includes a CSS file, although --css=none ." \
        "$?"
}


#--------------------------------
# * Does the --check switch validate the epub file?
#

function test_epubCheck () {
    local _EPUBPATH_BUILD

    clean_build

    _EPUBPATH_BUILD=$($_DAPSEXEC -d $_DCFILE epub --check 2>/dev/null | tail -n 1)
    assertTrue \
        ' └─ The epub command with --check failed' \
        "$?"
    # Test for epubcheck
    #
    grep -i "epubcheck" $_LOGFILE >/dev/null 2>&1
    assertTrue \
        " └─ The ePUB was not checked with epubcheck" \
        "$?"
}



#--------------------------------
# * Is the --name option correctly implemented?
#
function test_epubNAME () {
    local _BUILD_SUBDIR_NAME _EPUBPATH _EPUBPATH_BUILD
    _NAME="testsuite"

    clean_build

    _EPUBPATH_BUILD=$($_DAPSEXEC -v0 -d $_DCFILE epub --name $_NAME 2>/dev/null)
    assertTrue \
	" └─ Building an EPUB document with --name failed " \
       "$?"

    _EPUBPATH=$($_DAPSEXEC -v0 -d $_DCFILE epub-name --name $_NAME 2>/dev/null)
   assertTrue \
	' └─  Getting the filename for EPUB with --name failed ' \
       "$?"
   assertEquals \
       " └─ The resulting filename does not match the one retrieved with --epub-name: " \
       "$_EPUBPATH" "$_EPUBPATH_BUILD"

   # expr match does not work with Variables as search term, needs regexp

   _BUILD_SUBDIR_NAME=$(basename $(dirname "$_EPUBPATH_BUILD"))
   echo "$(basename $_EPUBPATH_BUILD)" | grep -q $_NAME
   assertTrue \
       " └─ String passed with --name ($_NAME) does not appear in the EPUB filename" \
       "$?"   
   assertEquals \
       " └─ The build subdirectory does not have the name supplied with --name: " \
       "$_NAME" "$_BUILD_SUBDIR_NAME"


}

#--------------------------------
# * Does the --rootid option work correctly?
#
function test_pdfRootidXsltparam () {
    local _EPUBNAME _EPUBNAME_BUILD _EPUBPATH_BUILD _ROOTID _XSLTPARAM

    _ROOTID=appendix
    _EPUBNAME=${_ROOTID}_en.epub
    _XSLTPARAM="--param \\\"hyphenate.verbatim=0\\\""

    clean_build

    _EPUBPATH_BUILD=$($_DAPSEXEC -d $_DCFILE --debug epub --rootid $_ROOTID 2>/dev/null | tail -n 1)
    assertTrue \
	' └─ Building an EPUB with --rootid failed ' \
       "$?"
    egrep -- "--stringparam\s+\"rootid=$_ROOTID\"" $_LOGFILE >/dev/null 2>&1
    assertTrue \
	' └─ Stringparam for ROOTID is not correctly specified when generating the EPUB-file' \
	"$?"
    _EPUBNAME_BUILD=$(basename $_EPUBPATH_BUILD)
    assertEquals \
	' └─ The resulting EPUB filename does not match the ROOTID:' \
	"$_EPUBNAME" "$_EPUBNAME_BUILD"
}

# source shUnit2 test
source $_SHUNIT2SRC
