#!/bin/bash
#
# Copyright (C) 2013 Frank Sundermeyer <fsundermeyer@opensuse.org>
#
# Author:
# Frank Sundermeyer <fsundermeyer@opensuse.org>
#
# Testing DAPS: Common functions
#

# ---------
# Usage
#
function usage () {
    echo "Something useful"
}

# ---------
# Remove the build directory
#
function clean_build() {
    rm -rf "${_DOC_DIR}/build"
}

# ---------
# Verbose error handling
#
function exit_on_error () {
    echo -e "ERROR: ${1}" >&2
    clean_build
    exit 1;
}

# ---------
# Print Test Header
#
function header () {
    echo
    echo "Test: $1"
    echo "=================================================="
}

# ---------
# Create tempdir
# 

function make_tempdir () {
    # Expects variable name and sets it to the path of the generated temp dir
    local _TMPDIR
    [[ -z $1 ]] && exit_on_error "${FUNCNAME[0]} was called with a empty parameter"
    _TMPDIR=$(mktemp -d -q ${SHUNIT_TMPDIR}/XXXXXXXXXX)
    if [ $? -eq 0 ]; then
	eval "$1='$_TMPDIR'"
    else
	exit_on_error " Creating a temporary directory failed. Skipping tests"
    fi
}

# --------
# Collect overall stats
#
function stats () {
    _FAILED=$(cat ${_TEMPDIR}/failed)
    _SKIPPED=$(cat ${_TEMPDIR}/skipped)
    _TOTAL=$(cat ${_TEMPDIR}/total)

    echo "$(( _FAILED + __shunit_assertsFailed ))" > ${_TEMPDIR}/failed
    echo "$(( _SKIPPED + __shunit_assertsSkipped ))" > ${_TEMPDIR}/skipped
    echo "$(( _TOTAL + __shunit_testsTotal ))" > ${_TEMPDIR}/total
}
