blank_issues_enabled: true
contact_links:
  - name: DAPS Community Support
    url: https://github.com/openSUSE/daps/discussions
    about: Please ask and answer questions here.
  - name: DAPS Documentation
    url: https://opensuse.github.io/daps
    about: Find more information in our documentation.
