#!/bin/bash
#
# Copyright (C) 2015-2018 SUSE Linux GmbH
#
# Author:
# Frank Sundermeyer <fsundermeyer at opensuse dot org>
#
###########################################################################
#
# BUILD man pages
#
# Subcommands: man only
#
###########################################################################
function build_man {
    local SHORT_OPTS LONG_OPTS SUB_CMD
    SUB_CMD=$1
    shift

    SHORT_OPTS="h"
    LONG_OPTS="help,nogzip,norefcheck,param,rootid:,stringparam:,subdirs"

    parse_args "$SHORT_OPTS" "$LONG_OPTS" "$SUB_CMD" "$@"
    eval set -- "$P_REMAIN_ARGS"

    #------ Computing the values returned from the parser -----
    if [[ 1 = "$P_HELP" ]]; then
        help_scmd_head "$SUB_CMD" "${HELP_SUBCOMMAND[$SUB_CMD]}"
        help_help
        help_nogzip
        help_norefcheck
        help_param
        help_rootid
        help_stringparam
        help_subdirs
        echo
        exit 0
    fi

    [[ -n "$P_NOGZIP" ]]     && export GZIP_MAN="no"
    [[ -n "$P_NOREFCHECK" ]] && export NOREFCHECK="1"
    [[ -n "$P_ROOTID" ]]     && export ROOTID="$P_ROOTID"
    [[ -n "$P_SUBDIRS" ]]    && export MAN_SUBDIRS="yes"
    [[ -n "$P_PARAMS" ]]       && export PARAMS="$P_PARAMS"
    [[ -n "$P_STRINGPARAMS" ]] && export STRINGPARAMS="$P_STRINGPARAMS"

    call_make "$SUB_CMD" "$@"
}
