#!/bin/bash
#
# Customized xep executable for daps
# Use environment variable VERBOSE to get more debugging output
#
__VERSION__="$Id: daps-xep 45418 2009-11-09 09:44:56Z ke $"

#
# Configuring variables
#
if test -s $USER/.daps/xep-config.xml; then
    ccecho "info" "Using XEP config file from $USER/.daps/xep-config.xml"
    export XEP_CONFIG_FILE=${XEP_CONFIG_FILE:-"$USER/.daps/xep-config.xml"}
fi
xep "$@"
