#!/bin/bash
# Customized fop executable for daps
# Use environment variable VERBOSE to get more debugging output

__VERSION__="$Id: daps-fop 43536 2009-08-11 22:10:56Z jw $"

#FOP_MEMORY=${FOP_MEMORY:-"-Xmx500m"}
FOP_STACK=${FOP_STACK:-"-Xss1024K"}
FOP_CONFIG_FILE=${FOP_CONFIG_FILE:-"/etc/daps/fop/fop-daps.xml"}

ADDITIONAL_FLAGS="$FOP_MEMORY $FOP_STACK" \
ADDITIONAL_JARS="batik-all excalibur/avalon-framework-impl" \
ADDITIONAL_OPTIONS="-Djavax.xml.transform.URIResolver=org.apache.xml.resolver.tools.CatalogResolver" \
fop -c ${FOP_CONFIG_FILE} "$@"
