#!/bin/bash
#
# Copyright (C) 2012-2015 SUSE Linux GmbH
#
# Author:
# Thomas Schraitle <toms at opensuse dot org>
#
# Customized xep executable for daps
# Use environment variable VERBOSE to get more debugging output
#

#
# Configuring variables
#
USER_XEP_CONFIG="$HOME/.config/daps/xep-config.xml"


if [[ -f $USER_XEP_CONFIG ]]; then
    ccecho "info" "Using XEP config file from $USER_XEP_CONFIG"
    export XEP_CONFIG_FILE=${XEP_CONFIG_FILE:-"$USER_XEP_CONFIG"}
fi
xep "$@"
