#!/bin/bash
#
# Copyright (C) 2012-2015 SUSE Linux GmbH
#
# Author:
# Thomas Schraitle <toms at opensuse dot org>
#
# webhelpindexer: creates index file(s) needed for the webhelp output
# taken from the build.xml file of  the DocBook XSL distribution
#

. /usr/share/java-utils/java-functions

MAIN_CLASS=com.nexwave.nquindexer.IndexerMain

# The DocBook XSLT stylesheet path:
# DB="/usr/share/xml/docbook/stylesheet/nwalsh/current"
# "${output-dir}/content"
#HTMLDIR=""
# "${webhelp.indexer.language}"
#INDEXERLANGUAGE=""
# "${html.extension}"
HTMLEXTENSION="${HTMLEXTENSION:-.html}"
# "${enable.stemming}"
DOSTEM="${DOSTEM:-true}"
# "${toc.file}"
TOCFILE="${TOCFILE:-}"

BASE_FLAGS="-Dorg.xml.sax.driver=org.ccil.cowan.tagsoup.Parser -Djavax.xml.parsers.SAXParserFactory=org.ccil.cowan.tagsoup.jaxp.SAXFactoryImpl"

if [[ -z ${DB} ]]; then
echo "Environment variable DB not set. DB points to the path for the DocBook XSL stylesheets"
exit 1
elif [[ -n $VERBOSE ]]; then
 echo "Using DocBook XSL stylesheet path: $DB"
fi

if [[ -n ${HTMLDIR} ]]; then
BASE_FLAGS="$BASE_FLAGS -DhtmlDir=${HTMLDIR} "
fi
if [[ -n ${INDEXERLANGUAGE} ]]; then
BASE_FLAGS="$BASE_FLAGS -DindexerLanguage=${INDEXERLANGUAGE} "
fi
if [[ -n ${HTMLEXTENSION} ]]; then
BASE_FLAGS="$BASE_FLAGS -DhtmlExtension=${HTMLEXTENSION} "
fi
if [[ -n ${DOSTEM} ]]; then
BASE_FLAGS="$BASE_FLAGS -DdoStem=${DOSTEM} "
fi
if [[ -n ${TOCFILE} ]]; then
BASE_FLAGS="$BASE_FLAGS -DtocFile=${TOCFILE} "
fi

CLASSPATH="$CLASSPATH:$(build-classpath-directory $DB/extensions ${VERBOSE:+2>/dev/null})"

# Set parameters
set_jvm
# set_classpath $BASE_JARS
set_flags $BASE_FLAGS
set_options $BASE_OPTIONS

# Let's start
run $args $PARAMS
