#!/bin/sh
#
# Taken from http://www.sagehill.net/docbookxsl/InstallingAProcessor.html#XercesWithSaxon
#
DBEXT="/usr/share/xml/docbook/stylesheet/nwalsh/current/extensions/saxon65.jar"
LIB="/usr/share/susedoc/lib"
CPATH="$LIB/saxon.jar:$DBEXT:$LIB/xercesImpl.jar:/usr/share/java/apache-xml-commons-resolver.jar:$CLASSPATH:$DTDROOT/etc/"

# Add Compare classes
for i in $LIB/Compare_*.class; do
CPATH=$i:$CPATH
done

# echo $CPATH
export CLASSPATH=$CPATH

java \
 -Djavax.xml.parsers.DocumentBuilderFactory=org.apache.xerces.jaxp.DocumentBuilderFactoryImpl \
 -Djavax.xml.parsers.SAXParserFactory=org.apache.xerces.jaxp.SAXParserFactoryImpl \
 -Dorg.apache.xerces.xni.parser.XMLParserConfiguration=org.apache.xerces.parsers.XIncludeParserConfiguration \
com.icl.saxon.StyleSheet \
   -x org.apache.xml.resolver.tools.ResolvingXMLReader \
   -y org.apache.xml.resolver.tools.ResolvingXMLReader \
   -r org.apache.xml.resolver.tools.CatalogResolver \
   -u \
$@
