---
name: daps-xmlwellformed

on:
  push:
    paths:
      - "python-scripts/daps-xmlwellformed/**"

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
        lxml: [4.6.0, 4.5.2, 4.4.3, 4.4.2]

    steps:
      - name: Install dependencies
        run: |
           sudo apt-get install -y libxml2-dev libxslt-dev
           pip install tox tox-gh-actions pytest
      - uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Output env variables
        run: |
           echo "GITHUB_WORKFLOW=${GITHUB_WORKFLOW}"
           echo "GITHUB_ACTION=$GITHUB_ACTION"
           echo "GITHUB_ACTIONS=$GITHUB_ACTIONS"
           echo "GITHUB_ACTOR=$GITHUB_ACTOR"
           echo "GITHUB_REPOSITORY=$GITHUB_REPOSITORY"
           echo "GITHUB_EVENT_NAME=$GITHUB_EVENT_NAME"
           echo "GITHUB_EVENT_PATH=$GITHUB_EVENT_PATH"
           echo "GITHUB_WORKSPACE=$GITHUB_WORKSPACE"
           echo "GITHUB_SHA=$GITHUB_SHA"
           echo "GITHUB_REF=$GITHUB_REF"
           echo "GITHUB_HEAD_REF=$GITHUB_HEAD_REF"
           echo "GITHUB_BASE_REF=$GITHUB_BASE_REF"
           echo "::debug::---Start content of file $GITHUB_EVENT_PATH"
           cat $GITHUB_EVENT_PATH
           echo "\n"
           echo "::debug::---end"

      - name: Call test suite for ${{ matrix.python-version }}-lxml${{ matrix.lxml }}"
        env:
          PY: ${{ matrix.python-version }}
        run: |
          PY=py${PY//./}
          echo "${PY}-lxml${{ matrix.lxml }}"
          cd python-scripts/daps-xmlwellformed
          tox --skip-missing-interpreters -e ${PY}-lxml${{ matrix.lxml }}
