#!/bin/bash
#First go at a xslt wrapper script for daps
#30.10.12 Kilian Petsch
#TODO:-options for saxon and xsltproc: with bareword, specific options come after, check after while loop if $1=S or X, then shift, then save rest ($@) in a variable and add this variable to the call in function processor
#     -remove unnecessary echo or make them silent (verbose option)
#     -update help with new options
#     -test stringparam and param with saxon

ME=$(basename $0)
# Help function to preserve readability of the while loop
usage () {
	echo "
	Usage: daps-xslt [OPTIONS] -o <OUTPUTFILE> -s <STYLESHEET> -f <XMLDOCUMENT> <XSLTPROCESSOR> [OPTIONS]
	This is a wrapper script for daps to define which xsltprocessor it should use.
	
	XSLT-STYLESHEET:
	-s,--stylesheet: Define the XSLT-stylesheet used,
	you may only define '-s' to use the default stylesheet
	 
	XML-DOCUMENT:
	-f,--file Define the XML-Document that should be used
	The above options are mandatory and need to be used.
	
	OUTPUT:
	-o,--output Create or write to an existing document
		
	The following options are optional:
	-x,--xinclude: do XInclude processing on document input
	--param name value : pass a (parameter,value) pair
	--stringparam name value : pass a (parameter, UTF8 string value) pair
	-h,--help: Display this help 
	
	After this options define your xsltprocessor (saxon6 or xsltproc),
	then specify the options unique to it.
	See saxon -h or xsltproc -h for these options" 
	
}
#function to call different processors and check for nonvalid options
processor () {
	if [ xsltproc = $PROC ]; then
		$PROC $REST $XIN ${PARAM} ${STRINGPARAM} $OP $STYLE $DOC
	elif [ saxon = $PROC ] && [[ -n $NONET || -n $NOVAL ]]; then
		echo "Error nonet and noval are xsltproc-only options"
		exit 3
	else  #saxon via a wrapperscript which enables XInclude, XML catalog etc.
		./daps-saxon $REST $OP $DOC $STYLE ${SPARAM} ${SSTRINGPARAN}  
	fi
}	
		
export POSIXLY_CORRECT=1

ARGS=`getopt -o "hxno:vs:f:" -l "help,xinclude,param:,stringparam:,nonet,output:,novalid, 
stylesheet:file:" -n "$ME" -- "$@"` 

eval set -- "$ARGS"
while true; do
	case "$1" in
		-h|--help)
			usage
			exit 0;;
		-x|--xinclude)
			XIN="--xinclude" #only needed in xsltproc
			shift;;
		--param) 
			if [[ "$2" =~ \= ]]; then
                            	PARAM=${2/=/ }
                    		PARAM="$1 $PARAM "
				SPARAM+="$2 "
				echo ${PARAM}
			else
				echo "Error. --param requires 'KEY=VALUE' as options"
				exit 2;
			fi
			shift 2;;
		--stringparam)
			if [[ "$2" =~ \= ]]; then #Test for equal sign 
                            	STRINGPARAM=${2/=/ }
                           	STRINGPARAM="$1 $PARAM "
				SSTRINGPARAM+="$2 "
				echo ${STRINGPARAM}
			else
				echo "Error. --stringparam requires 'KEY=VALUE' as options"
				exit 2;
			fi
			shift 2;;
		-s|--stylesheet)
			echo "Stylesheet: $2"
			STYLE=$2
			shift 2
			;;
		-f|--file) #option to add the file to prevent options from using filename as their parameter
			DOC=$2
			echo "Using file" $DOC
			shift 2;;
		-o|--output)
			echo "Generating output file" $2
			OP="-o $2"
			shift 2;;
		--)
			shift ;
			break;; 
	esac
done
unset POSIXLY_CORRECT
if [[ xsltproc = $1 || saxon = $1 ]]; then
	PROC=$1
	shift;
else
	echo "Error nonvalid processor"
	exit 1;
fi
REST=$@
echo $REST
 
#Now there should be now leftover parameters
#Check if all mandatory components are given
if [ -z "$PROC" ] || [ -z "$STYLE" ] || [ -z "$DOC" ]; then
	echo "Error necessary argument missing! Make sure you have all necessary components defined"
	exit 6;
else
	echo $PROC $STYLE
fi 
processor  #Calling processor function
	exit 0;
